{
 "title": "wis2-downloader monitoring dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Messages received",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate({container_name=\"wis2-downloader\"} |= `Message received` [1m])"
    }
   ]
  },
  {
   "title": "Files downloaded",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate({container_name=\"wis2-downloader\"} |= `Download` [1m]))",
     "legendFormat": "download per minute"
    }
   ]
  },
  {
   "title": "WIS2 downloader logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{container_name=\"wis2-downloader\"} |= ``"
    }
   ]
  }
 ]
}